{"tests": [{"data": {"status": "error", "tool_id": "nucleR", "time_seconds": 0.4008150100708008, "inputs": {"seq_type": "paired", "hthres": "0.4", "pcKeepComp": "0.02", "wthres": "0.6", "threshold|thresholdPercentage": "35", "rdata_file": {"src": "hda", "id": "2891970512fa2d5a"}, "width": "147", "minoverlap": "80", "dyad_length": "50"}, "tool_version": "0.1", "problem_log": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/home/user/galaxy-central/test/functional/test_toolbox.py\", line 99, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/home/user/galaxy-central/test/functional/test_toolbox.py\", line 36, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/home/user/galaxy-central/lib/galaxy/tools/verify/interactor.py\", line 738, in verify_tool\n    raise e\nRunToolException: Error creating a job for these tool inputs - Error executing tool: list index out of range\n", "test_index": 0, "problem_type": "galaxy.tools.verify.interactor.RunToolException", "execution_problem": "Error creating a job for these tool inputs - Error executing tool: list index out of range"}, "id": "functional.test_toolbox.TestForTool_nucleR.test_tool_000000", "has_data": true}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 1, "num_failures": 0, "num_tests": 1}}